Skip fonts we can't parse due to reEndMarker not matching
All zip fonts and some non-zip fonts fail to parse with this error:

e.g. for `ascii12`:

```
Traceback (most recent call last):
  File "pyfiglet/__init__.py", line 349, in loadFont
    width, letter = __char(data)
                    ^^^^^^^^^^^^
  File "pyfiglet/__init__.py", line 316, in __char
    end = self.reEndMarker.search(line).group(1)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'
```